sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile  -t alpine_python   .

script:
    - docker run -i alpine_python   > result

    - echo "==> Validating the test results..."
    - sh -c "[ -s result ]"

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/